version: '3.8'

services:
  frigate:
    image: blakeblackshear/frigate:latest
    container_name: frigate
    volumes:
      - ./frigate/config:/config
      - ./frigate/media:/media
    ports:
      - "5000:5000"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
      - "8097:8097"
      - "8098:8098"
      - "8099:8099"
    environment:
      - FRIGATE_CONFIG_FILE=/config/config.yml
